import { printStuff } from './printStuff';
import { func1 } from './autogenerated/file1';

const workerScope = self;

// Handle browser messages
workerScope.addEventListener('message', (_e) => {
    printStuff();
    func1();
    workerScope.postMessage({type: 'complete'});
});
